name: Deploy Java App to GCP VM

on:
  push:
    branches:
      - main  # Change to your main deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Restore keystore.p12 from GitHub Secret
      run: |
        mkdir -p src/main/resources/cert
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > src/main/resources/cert/keystore.p12

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17' 

    - name: Set up Maven 3.9.9
      run: |
        curl -fsSL https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz | tar xz
        echo "$(pwd)/apache-maven-3.9.9/bin" >> $GITHUB_PATH
        mvn -version
    
    - name: Build the project
      run: |
        mvn clean package -DskipTests  # Skip tests for faster builds

    - name: Generate Tag
      id: generate_tag
      run: |
        TAG_NAME="v$(date +'%Y%m%d-%H%M%S')"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "Generated Tag: $TAG_NAME"

    - name: Create Git Tag
      run: |
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload JAR to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        files: target/*.jar
        body: "Auto-generated release ${{ env.TAG_NAME }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/demo-spring-app:${{ env.TAG_NAME }} .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/demo-spring-app:${{ env.TAG_NAME }}

    - name: Set up SSH connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ vars.GCP_VM_IP }} >> ~/.ssh/known_hosts

    - name: Deploy Docker Container on GCP VM
      run: |
        ssh -i ~/.ssh/id_rsa ${{ vars.GCP_VM_USER }}@${{ vars.GCP_VM_IP }} << 'EOF'
          sudo docker stop demo-spring-app || true
          sudo docker rm demo-spring-app || true
          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/demo-spring-app:${{ env.TAG_NAME }}
          sudo docker run -d --name demo-spring-app -p 8080:8080 -p 443:443 \
            -e KEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" \
            -v /home/${{ vars.GCP_VM_USER }}/config/application.properties:/app/application.properties \
            ${{ secrets.DOCKER_HUB_USERNAME }}/demo-spring-app:${{ env.TAG_NAME }}
        EOF